name: mapazimslupsk
description: Schedule app for municicpal public transport in the city of Slupsk (Poland).

publish_to: 'none'

version: 1.7.14+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.6
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.8.1
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_spinkit: ^5.0.0
  http_parser: ^4.0.0
  firebase: ^9.0.1
  firebase_analytics_web: ^0.5.4+3
  firebase_messaging: ^14.6.3
  flutter_launcher_icons: ^0.13.1


  cupertino_icons: ^1.0.3
  geolocator: ^9.0.2
  flutter_blue: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true